title: Marion Chauveau
logo: /assets/img/ProfilePicture_circle.png
description: Postdoctoral researcher
show_downloads: false
email: marion.chauveau<at>univ-grenoble-alpes.fr
twitter_username: Marion_Chauveau
theme: jekyll-theme-minimal

include:
  - _pages

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: # true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      # layout: header_free
      layout: default


# Custom navigation links
nav:
  - title: "Publications"          # This will appear as the link text
    url: /publi           # Internal links point to your pages
  - title: "Hobbies"
    url: /Hobbies
#  - title: "Readings"
#    url: /Readings
